// <auto-generated />
using System;
using BokuNoGame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BokuNoGame.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210508102413_IntegrationInfo")]
    partial class IntegrationInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);


            modelBuilder.Entity("BokuNoGame.Models.IntegrationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalGameId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSystemDescriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternalGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntegrationInfos");
                });

#pragma warning restore 612, 618
        }
    }
}
